language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - android-25
    - build-tools-25.0.3
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services
  licenses:
      - 'android-sdk-preview-license-.+'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+' 
before_install:
  - cd App
  - chmod +x gradlew
script:
  - ./gradlew build connectedCheck
